### PR TITLE
UI changes in mixin deposit and withdraw popup

### PR DESCRIPTION
**Pull request by umairkhannn**

### CODE REVIEW

**Review by f8daniel — APPROVED** [review]
lgtm

**Comment by umairkhannn** [comment]
@f8daniel @trevelyan dont merge this pull request yet, Karl is testing these changes.

**Comment by karlsaito** [comment]
can you provide a screenshot @umairkhannn

**Comment by umairkhannn** [comment]
@karlsaito screeenshots provided in the issue linked with this pull request: 
https://github.com/SaitoTech/saito-lite-rust/issues/442

**Review by trevelyan — APPROVED** [review]
lgtm

**Pull request merged**
