### PR TITLE
Redsquare post username fix

### PR DESCRIPTION
**Pull request by davikstone2**

### CODE REVIEW

**Comment by karlsaito** [comment]
@umairkhannn  requesting for review

**Review by trevelyan — CHANGES_REQUESTED** [review]
No.

This is handled through app.browser.addUsernamesToDom()

please check on proper implementation before grabbing stuff like this

**Comment by trevelyan** [comment]
This cannot be merged.

**Comment by arpee** [comment]
This looks solid. Am wondering about adding these two functions to browser.ts - but this good for now.

**Pull request closed without merging**
