### PR TITLE
Crypto history overlay

### PR DESCRIPTION
**Pull request by umairkhannn**
image

### CODE REVIEW

**Comment by arpee** [comment]
Please replace the ">>" with https://fontawesome.com/icons/arrow-up-right-from-square?f=classic&s=solid

Other than that - solid, thanks.

**Comment by umairkhannn** [comment]
Added font-awesome icon @arpee 

image

**Comment by arpee** [comment]
Great thanks. I just reaslised though, that the link should open in a new tab too...

**Comment by umairkhannn** [comment]
@arpee updated link with target="_blank" for new tab.

**Pull request merged**
