### PR TITLE
Feature/chess improvements

### PR DESCRIPTION
**Pull request by umairkhannn**

### CODE REVIEW

**Review by f8daniel — COMMENTED** [review]
Looks pretty good. There are a few things I would request changing:

###  Buttons 

1. I would swap the order of  move_accept and move_reject. I expect "accept" to be on the right.
2. Why does move_accept turn red on hover? Shouldn't it be green?
3. I would dynamically show/hide the move_accept and move_reject buttons. They should only appear once you have made a move on the board. 

### Status
4. Why is controls column so big? Bigger than the chess board itself? I know the literal answer is that is how flexbox works in css, but from a design perspective, it's max-height should be limited.
5. Status and Turn can be combined into one row

```
 <div class="tool-cont">
        <div> 
               <div class="tool-item item-name">TURN</div>
               <div class="tool-item item-detail turn-shape" id="turn-shape" style="background-color: rgb(255, 255, 255);"></div>
        </div>
        <div class="tool-item item-detail" id="status"></div>
 </div>

```
6. Add the identicon for the opponent. As in the above code, you can nest the divs so that the identicon is in the left hand column. 
7. Pieces captured should be the final item in the column with expandable space as pieces are captured.

### Board
8. The shading on the board (when you hover over a piece) looks off. The white squares have a good contrast with a very dark color, but the black squares disappear. Either adjust the shades for a good contrast, or it may be better to have a single color for highlighting (regardless of whether the underlying square is white or black)

**Comment by umairkhannn** [comment]
@f8daniel thanks for feedback, implementing some of these changes.

**Comment by arpee** [comment]
I think 7 is wrong - at least for me I want the pieces in value order so I can make a quick assessment of 'who is ahead'.

Would like a resign button.

**Comment by umairkhannn** [comment]
@arpee noted.

**Comment by umairkhannn** [comment]
Current state for reference.

Screenshot from 2022-05-31 04-46-27

**Comment by umairkhannn** [comment]
@arpee resign button not showing an existing bug on live. Taking care of it along with other changes.

Screenshot from 2022-05-31 11-29-25

**Comment by umairkhannn** [comment]
PR updated with following changes:

1. Swapped accept and reject button positions
2. Accept button green on hover fix
3. Show/hide accept reject buttons dynamically after each move
4. Re style control column, small and sleek
5. Combined status and turn into one box
6. Added identicon for opponent
7. Added copy button for copying opponent public address
8. Change shadding of boxes when moving piece
9. Made layout responsive for different screen sizes
10. Resign icon added

**Pull request merged**
