### PR TITLE
Standard loader for crypto transfers

### PR DESCRIPTION
**Pull request by umairkhannn**
Screenshot from 2023-09-18 11-03-09

### CODE REVIEW

**Comment by arpee** [comment]
image


Can I suggest that rather than removing this message it be made a 'siteMessage' with the 1000ms visibility?

**Comment by umairkhannn** [comment]
@arpee  reason I commented this salert() is because there is an issue where this message keep popping repeatedly after refresh.
Have to fix it to make it appear only once after deposit, not after every refresh.

**Comment by umairkhannn** [comment]
@arpee siteMessage() added

**Comment by arpee** [comment]
Brilliant, thanks.

**Pull request merged**
