### PR TITLE
Create universal-compiler

### PR DESCRIPTION
**Pull request by cressidave**
Compiler script refactored to NodeJs to make compilation simpler for end-users on any OS.

### CODE REVIEW

**Comment by cressidave** [comment]
Compiler script refactored to NodeJs to make compilation simpler for end-users on any OS.

**Comment by davikstone2** [comment]
### Comments 

Screenshot 2022-05-02 at 22 14 40

The above error is still shown on Mac OS when attempting to compile

**Comment by cressidave** [comment]
> ### Comments
> Screenshot 2022-05-02 at 22 14 40
> 
> The above error is still shown on Mac OS when attempting to compile

Are you running the universal-compiler? (node universal-compiler.js)
That error looks like the original compiler bash error

**Comment by karlsaito** [comment]
@cressidave , what's your telegram? would be better to discuss this on telegram :)

**Comment by trevelyan** [comment]
[ thank you Dave ]

script placed in new /scripts subdirectory, slightly modified so webpack works with new dir structure.

submission is already merged into staging , and will go into master with the next update

i will update the wiki instructions. it is triggered by:

> npm run init

closing this PR as already done!

**Pull request closed without merging**
